/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handsome_safe_MainActivity */

#ifndef _Included_com_handsome_safe_MainActivity
#define _Included_com_handsome_safe_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handsome_safe_MainActivity
 * Method:    helloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_handsome_safe_MainActivity_helloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
